# --- Stage 1: Build ---
FROM maven:3.9-eclipse-temurin-17-alpine AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# --- Stage 2: Runtime ---
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

RUN mkdir -p /app/config
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]